//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
export default function Note9() {
    const noteIndex = 8;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>Through the Tunnels</h2>
        <p>I have been seeing some people describe life at the University of Virginia, and university as general, as a never-ending "rat-race." Everyone is trying to get ahead of each other at any cost, so they say. The obvious question then is, how do rats win a race? The answer: using tunnels. Fortunately, I know of the best tunnels at UVA. With the University being as old as it is, there are bound to be some hidden pathways and secrets.</p>
        <p>I do not have much time to write nowadays, so instead I will present a video of myself walking through my favorite secret at my University. The Engineering School tunnels allow you to walk for approximately five straight minutes underground, winding through various twists and turns of different department offices and labs. Enjoy this video of me navigating from the second floor study lounge all the way to the computer science building without going outside for a single second. Perfect for a computer science major! I recommend watching on YouTube in a separate tab.</p>
        <div className="video-container">
            <iframe src="https://www.youtube.com/embed/yRCQIwdHblo?si=I7l1X3WAaL9m4wzw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen />
        </div>
        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
