//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
import storm from './storm.jpg';
import stretch from './stretch.jpg';
export default function Note13() {
    const noteIndex = 13;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>Cardinal One and Cardinal Two</h2>
        <p>At halftime of the Louisville football game this season, my usual negative self was quick to remind everyone I was watching with that UVA was in a surprisingly familiar position. While it is easy to forget now, the football team was in a virtually identical position standings-wise while at halftime at Louisville. Both <a href="https://www.espn.com/college-football/game/_/gameId/401754554/virginia-louisville" target="_blank" rel="noopener noreferrer">this year</a> and <a href="https://www.espn.com/college-football/game/_/gameId/401635578/louisville-virginia" target="_blank" rel="noopener noreferrer">last year</a>, in its fifth game of the season, Virginia football was 4-1 overall, and tied up against Louisville at halftime. On paper, the situation this year should have been even worse, since UVA was on the road this year, as opposed to having home field advantage against Louisville last year. However, I think almost anyone who watched these two games would agree that the overall “vibe” of the games was completely different. It really felt like UVA had a shot in this game (which they obviously did since they won), but more importantly, it felt like it actually mattered.</p>
        <p>There is an old saying that “winning solves all problems” when it comes to sports games and passionate fans. It is a lot easier to tolerate a $10 mushy hot dog when your football team is up by 27 on the field than when they are down by 27\. It is especially easier to tolerate that hot dog when you have a nationally talked about team that is playing for something more than just the current game, such as a conference title or a playoff spot. Finally, possibly most importantly, you can better soak up the price of that hot dog when you are surrounded by tens of thousands of other fans who are all just as passionate as yourself and excited about the future. The passion is what made the difference between this year’s Louisville game and last year’s Louisville game, and all future games in the season. But where did the passion come from?</p>
        <p>While winning can solve all problems, beating up inferior competition is not enough to ignite a fan base. Anyone can beat up East Podunk State University 50-0 (just look at JMU’s schedule). To get fans fired up after years of being a bottom feeder, a statement win, while everyone is watching, is needed. Winning at the wrong times does not lead to much. Just look at <a href="https://augustafreepress.com/news/scott-german-they-had-a-uva-football-game-and-nobody-came/" target="_blank" rel="noopener noreferrer">this article</a> about the Louisville game last year, complaining about virtually everything at the game. Even though Virginia football was 4-1 and playing a great team, the football game was at noon during reading weekend, and UVA attendance was abysmal. Preferably, the statement win should be in prime time in a crowded stadium against a top-ranked team. This leads me to my “Virginia football master thesis” of the season: Florida State saved the Virginia football program.</p>
        <figure className="note-figure">
            <img src={stretch} alt="The UVA football team stretching before a performance at the Gator Bowl (to be discussed later)." className="note-inline-image" />
            <figcaption>The UVA football team stretching before a performance at the Gator Bowl (to be discussed later).</figcaption>
            <span className="image-source"><a href='https://www.youtube.com/watch?v=Pckq19XeKV4' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>The Seminole Saviors</h2>
        <p>Everything lined up perfectly schedule-wise for UVA football this year, and the FSU game was no exception. FSU was ranked \#8 in the country after beating Alabama before proceeding to beat up two cupcake schools. At the time it truly felt like FSU was unstoppable, and Virginia fans were constantly being told by the media that while this Cavalier team was improved from previous years, this game was just too far out of reach. For once though, instead of just laying down and accepting that this team was destined to be a bottom feeder forever, the UVA team, fans, and students were not willing to accept this narrative.</p>
        <p>Despite being in my third year of college, the FSU game was the first time I can remember a majority of students around Grounds actually talking about a football game and planning their weekend schedules around it. For most students at UVA, the football games have historically been background “entertainment” (if you can call it that) for other things going on over the weekend. This time, students were hyped, and I was even more hyped than usual. The Friday of the game became a classes-optional sort of day, and most classes were only generously half full as students got ready for the game.</p>
        <p>The actual game provided the “perfect storm” for what some have called the greatest field storm of all time. It was a high-scoring affair with constant lead changes between the two teams. It was a Friday night on prime-time ESPN television. FSU was theoretically a top-10 team in the country and was supposed to be unbeatable. Florida State fans, as expected, were being quite obnoxious both in-person and online in supporting their team. There were no restrictions about who could be on the hill, since security had no recent experience with any field stormings (except from the other team). The game previously looked like it was going to be over at the end of regulation, until Florida State converted a miracle 4th-and-10, so fans were already in position to storm the field. Finally, the final play occurred in 2OT, so FSU was coming towards the student section, not away from it. All of that factored into what may have been the greatest field storm of all time.</p>
        <p>The result of the game led to two things that Virginia football has not had since the 2019 season: national attention, and large-scale fan support. Articles were written about UVA football in sources going tall the way up to the <a href="https://apnews.com/article/virginia-florida-state-field-rush-5032236b12969cf1f2420321a3912b2c" target="_blank" rel="noopener noreferrer">official AP.</a> With UVA becoming ranked for the first time since 2019, there was now reason for the national media to care about how the football team did. After UVA beat Louisville the next week, there was little room to deny that this year’s team was finally legit. Fans were ready to come out and support a winning football team, and I certainly was as well. After the Louisville game, I went to 7 of the remaining 8 Virginia football games in 5 different cities, with the only exception being at Cal for slight logistical reasons. The following is a recap of the fan and marching band experiences at the next few games.</p>
        <figure className="note-figure">
            <img src={storm} alt="The nationally-known storming of Scott Stadium. Some have called it the greatest field storm of all time." className="note-inline-image" />
            <figcaption>The nationally-known storming of Scott Stadium. Some have called it the greatest field storm of all time.</figcaption>
            <span className="image-source"><a href='https://www.youtube.com/watch?v=Pckq19XeKV4' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>On the Move</h2>
        <p>The video attached shows my travel and performances with the marching band that occurred throughout the UVA season after the FSU game. The first section combines four separate performances of the “pregame” performances from the band and shows the entrances of the football teams. For a full pregame performance, see the <a href="https://www.youtube.com/watch?v=4h0vC_tdmz4" target="_blank" rel="noopener noreferrer">previous video</a> on the Stanford football game. The next portion of the videos shows road travel to the UNC game, Duke game, ACC Championship, and Gator Bowl, as well as my own reaction to some key plays. The halftime performance at the Gator Bowl is included. Finally, random humorous or silly clips from the season are included at the end of the video in no particular order. Let me know if you are curious about any additional details from a particular game. I will likely make one more band-related article due to the positive reception to the previous one, and to fulfill a promise to another member earlier in the year. Once again, thank you FSU and Tony Elliott for saving Virginia football.</p>
        <div className="video-container">
        <iframe 
            src="https://www.youtube.com/embed/Pckq19XeKV4?si=sAFWUzKUoLQTmIci" 
            title="YouTube video player" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share" 
            referrerpolicy="strict-origin-when-cross-origin" 
            allowfullscreen>
        </iframe>
        </div>
        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
