//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import plan from "./plan.pdf";
import casestudy from "./casestudy.pdf";
import telecom from "./telecom.pdf";
import openai from "./openai.pdf";
import './../notes_page.css';
export default function Note9() {
    const noteIndex = 9;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>If I Had More Time</h2>
        <p>As he was sending a long message to his friend, Mark Twain famously quipped, <q>If I had more time, I would have written a shorter letter.</q> As someone who has quite a verbose style of writing (observe this very sentence), I can heavily relate to this anecdote. The less time I have to think, the more time I will spend rambling about completely irrelevant topics. I often wonder about how much of what I write, particularly in academic and professional contexts, are ever actually read been anyone. I had a realization as I was creating a particularly long and tedious government-related software documentation at work that it was very unlikely anyone would ever read many of the words on the page. Instead, they would only look at the general outline for a review, and specific sections if they needed help.</p>
        <p>I have been incredibly busy over the past few months, and thus have barely any time to write outside of academic or school papers. Thus, I figured I would put out the most boring papers I have written over the past four semesters. However, instead of publishing my greatest works, I have decided to put out my most boring and tedious writings. Try not to fall asleep. My life over the past months has been fascinating, but for now I will make it appear as dull as possible. </p>
        <h2>UVA 2030 Strategic Plan Analysis</h2>
        <p>This paper was the first written for CE 3010 - Project Business Planning, a class designed around managing the logistics and financials a hypothetical construction project occurring at UVA. To begin, our task was to understand and explain UVA’s strategic vision for the next five years, to ensure our project idea was aligned with our funder’s goals. Needless to say, this is not the most thrilling topic for a paper. </p>
        <iframe src={plan} width="100%" height="800px" />
        <h2>Fighting the Adpocalypse</h2>
        <p>For STS 2600 - Engineering Ethics, an "extra credit" assignment was to create a fake case study involving an ethical dilema related to the field of study you were in. I chose to create an ethical dilema related to web accessibility, a topic I am very interested in and one that is often underappreciated. I like the topic of this paper, but there were so many strange requirements related to its submission, such as having to give a "usage authorization".</p>
        <iframe src={casestudy} width="100%" height="800px" />
        <h2>Disrupting the Telecom Status Quo</h2>
        <p>This is an entire paper on T-Mobile's market position in the Telecom industry. As boring as that sounds, the research for this was actually decently interesting. This was my group's final paper for EBUS 1800 - Engineering Business, and it was one of the most useful classes I have taken here. We decided to write a paper about the telecom industry because it is less "exciting" that other, more modern industries, and we knew noone else would be writing about it.</p>
        <iframe src={telecom} width="100%" height="800px" />
        <h2>OpenAI Goes Private</h2>
        <p>For some reason, I decided to take DS 1001 - Intro to Data Science in my second semester at UVA. This was not a requirement nor did it count as an elective, so I am not sure why I took the class. Still, it ended up being one of my favorite classes I took here, mostly due to the two very knowledgable professors. There was one class where the professor compared the disruption that came from the iPhone to the disruption of the printing press, and I still find that to be one of the most poignant comparisons ever made in a class. This paper was written on OpenAI going private, a novel topic at the time. </p>
        <iframe src={openai} width="100%" height="800px" />
        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
