//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
import darden from './darden.jpg';
import president from './president.jpg';
export default function Note12() {
    const noteIndex = 12;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>More Consultants Now</h2>
        <p>If there’s one thing America needs more of, it is certainly consultants. <a href="https://www.youtube.com/watch?v=uG3uea-Hvy4" target="_blank" rel="noopener noreferrer">Could you imagine a world without consultants</a>? Move over doctors and firefighters. One shudders to imagine the loss to shareholder value that could occur without the suit-and-tie heroes from freedom-fighting organizations such as McKinsey, Bain, and BCG. Fortunately for us, we do live in a world of consultants, and plenty of them. On Friday, the Board of Visitors at the University of Virginia <a href="https://news.virginia.edu/content/university-virginia-names-scott-c-beardsley-universitys-10th-president" target="_blank" rel="noopener noreferrer">announced</a> that University’s 10th president would be Scott C. Beardsley, the dean of the UVA business school, and former 26-year McKinsey employee. I <a href="https://www.josephmoran.org/notes/jim" target="_blank" rel="noopener noreferrer">previously have talked at length</a> about my modest confusion regarding the firing of Jim Ryan, a lifelong educator and scholar. To replace him, we have a lifelong businessman.</p>
        <p>I sometimes wonder in jest if there is any reason to major in anything besides business, economics, or “LinkedIn Engineering.” Playing devil’s advocate, the most common reasons why people choose their major usually come down to either passion, money, or a desire to change the world. A business degree and the right connections could theoretically accomplish all of these items better than any other major could. The high-paying STEM careers that many lifetime go-getters spend years in school preparing for all will eventually some sort of cap on the amount of money that can be earned. Even a doctor who starts their own practice still has to deal with insurance companies, <a href="https://www.aha.org/system/files/media/file/2023/06/Private-Equity-and-Health-Insurers-Acquire-More-Physicians-than-Hospitals-Infographic.pdf" target="_blank" rel="noopener noreferrer">which effectively act as their bosses</a>.</p>
        <p>The only way to have an ever-growing income stream is to run a business yourself, or be another high-level executive. Once you have enough money to live comfortably off investments, you are able to pursue or fund whatever other passions, goals, or subject matter interests you still have. Sacrifice a few years of your early career, then follow your passions. Thus, a money-making C-suite position from a business degree can do more to accomplish one’s goals than any other degree can. As President Beardsley may know, McKinsey likes to use the phrase <a href="https://www.leadership-choices.com/blog/insecure-overachievers-and-their-beliefs" target="_blank" rel="noopener noreferrer"><q>insecure overachievers</q></a> to describe the goals of their young employees. These archetypal consultants are following my quixotic argument given here. Is it true? I am not sure. Maybe I will write more on the topic in the future.</p>
        <p>Regardless of my opinion on the matter, the original topic I was going to write about was not the new president, since that news was just announced. Rather, I intended to highlight some of the long-term projects I have worked on in my classes this semester. Now that McKinsey is in charge of the University and I may have to “<a href="https://www.youtube.com/watch?v=O95fnszzI6I" target="_blank" rel="noopener noreferrer">prove my worth</a>” so I don’t get laid off (sorry, not laid off, “corporate restructuring”) as a student, now seems like the perfect time.</p>
        <figure className="note-figure">
            <img src={president} alt="I have to admit, President Beardsley has quite a charming smile. Got to have that for making deals." className="note-inline-image" />
            <figcaption>I have to admit, President Beardsley has quite a charming smile. Got to have that for making deals.</figcaption>
            <span className="image-source"><a href='https://news.virginia.edu/sites/default/files/Header-SF-PresidentMainStory\_StephanieGross.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>Long-Term Projects</h2>
        <p><i>Projects will be posted to the <a href="/work">Past work</a> page before the end of the year, and links will be updated here. Apologies for the delay.</i></p>
        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
