//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
import louisville from './louisville.jpg';
import ncstate from './ncstate.jpg';
import tech from './tech.jpg';
import tony from './tony.jpg';
import unc from './unc.jpg';
export default function Note7() {
    const noteIndex = 7;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>A Turning Point</h2>
        <p>No matter what ACC or UVA football news source you read, there is one line that will inevitably appear: “This is a make or break year for Tony Elliott.” As head coach of the Cavaliers for the last three years, he has only amassed a 11-23 win-loss record, which is extremely poor for a Power Four program such as UVA. Of course, in his first year he and the team had to endure the horrible shooting of three players, so this year can largely be overlooked. In 2023, UVA finished with an inexcusable 3-9 record, that included a loss to non-power five school James Madison, a 42-14 loss to “rival” Maryland, and worst of all a 55-17 home loss to actual rival Virginia Tech. As someone who was at every single home game that year, it was truly a painful experience.</p>
        <p>The team marginally improved in 2024, starting out 4-1 with exciting wins over ACC rivals such as Wake Forest and Boston College. However, this success was short lived as UVA would go on to lose 6 of the next 7 games, including blowout losses to North Carolina, SMU, Notre Dame, and Virginia Tech yet again. Still, despite the poor end-of-season performance, Elliott demonstrated that he is capable of winning football games. Injuries and locker room issues can partially be blamed for the poor performance at the end of the year. I especially blame QB Anthony Colandrea, who had a very obvious negative attitude that brought the team down with him. Thankfully, he has transferred to UNLV and a new team and lead QB have been brought in.</p>
        <p>The era of the transfer portal and conference realignment in college football has brought much hardship to many lower-ranked teams. Bad teams will usually lose their top players to better schools, making the bad worse and the good even better. One of the very few exceptions to this rule is Virginia Football. UVA has had very little past success on the football field, especially in recent years. However, the one thing UVA has a lot of are rich donors, being a school with one of the twenty largest endowments in the country. This year, a single multi-million dollar anonymous donation prompted many more million-dollar donations to Virginia football. With this money, UVA bought some of the top players on the market, including new quarterback Chandler Morris. How will this new team fare, and will Tony Elliott catch his big break, or be out of Charlottesville?</p>
        <figure className="note-figure">
            <img src={tony} alt="Coach Tony Elliott, known to friends as C.T.E., looking fresh in his suit." className="note-inline-image" />
            <figcaption>Coach Tony Elliott, known to friends as C.T.E., looking fresh in his suit.</figcaption>
            <span className="image-source"><a href='https://upload.wikimedia.org/wikipedia/commons/8/80/Tony_Elliott_UVA_NIL_%28cropped%29.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>2025 UVA Football Predictions</h2>
        <p>I figured the best way to take a look at the UVA football season would be to go through each game and assign a percent win chance to each one. I will also throw out a guess for the score, but this will likely be highly inaccurate. The win percentages will then be added up to determine an estimate for the final record.</p>
        <h2> August 30 - Vs. Coastal Carolina</h2>
        <p>Last year, UVA played a road game in Conway, South Carolina, and soundly defeated the Chanticleers 43-24. With an improved roster this year, and the game being played at home, there is little reason to believe UVA should be losing this game. While Coastal Carolina has also improved its roster, the talent gap between a power four program like UVA and a group of five schools like CCU is just too large to overlook. UVA has already opened as a 12.5 touchdown favorite in this game, and I believe the margin of victory will be far greater than that.</p>
        <p>Chance of Victory: 85%</p>
        <p>Predicted Score: UVA 38 - CCU 10</p>
        <p>Estimated Record: 0.85 W - 0.15 L</p>
        <h2> September 6 - At NC State</h2>
        <p>Due to conference realignment drama, UVA is playing NC State as an out-of-conference game, meaning that despite both teams being in the ACC, this game will not count towards ACC final standings. Both of these teams are about equal talent-wise, and this game should be considered a toss-up by most metrics. Despite my bias towards UVA, I will give the slight edge to NC State here purely due to this being a road game for UVA. However, this game does remind me of the Wake Forest game last year, where UVA came in with a clutch fourth-quarter comeback.</p>
        <p>Chance of Victory: 45%</p>
        <p>Predicted Score: UVA 27 - NCSU 30</p>
        <p>Estimated Record: 1.3 W - 0.7 L</p>
        <figure className="note-figure">
            <img src={ncstate} alt="Two years ago, UVA lost to NC State on a last-minute field goal at home." className="note-inline-image" />
            <figcaption>Two years ago, UVA lost to NC State on a last-minute field goal at home.</figcaption>
            <span className="image-source"><a href='https://virginiasports.com/imgproxy/yVRVL-v6mcurpny8DgY2PRm1CymAIe49xClwU-QsbSo/fit/1500/1500/ce/0/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3Zpcmdpbmlhc3BvcnRzLWNvbS8yMDIzLzA5LzI4YjdmZDgyLTA4MGE3NjY4LmpwZw.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2> September 13 - Vs. William & Mary</h2>
        <p>As an FCS school, William and Mary is quite literally out of UVA’s league. UVA is very fortunate to be able to play William and Mary every other year, as any FCS game should be considered a free win for a power four program. Even the terrible 2023 UVA football team was able to secure a 27-13 win against W&M. No one, not even my friends at William and Mary, expect the Tribe to win this game. Still, I will give a shoutout to William and Mary for being a very beautiful and intelligent school.</p>
        <p>Chance of Victory: 95%</p>
        <p>Predicted Score: UVA 45 - W&M 7</p>
        <p>Estimated Record: 2.25 W - 0.75 L</p>
        <h2> September 20 - Vs. Stanford</h2>
        <p>One of the funniest parts of UVA’s schedule this year is that the in-conference game is at home against Stanford, a very famous school that is definitely on the Atlantic Coast. In what I have seen some news sources refer to as the “battle of the brains,” UVA should come out with a dominant win. At the time of writing this, Stanford has already lost their Week 0 matchup to an incompetent Hawaii team, and there is little reason to see the Cardinal improving. Stanford is a bottom five power school team that historically has cared even less about football than UVA has. This should be an enjoyable, yet likely quite empty, home game for UVA.</p>
        <p>Chance of Victory: 80%</p>
        <p>Predicted Score: UVA 33 - STAN 17</p>
        <p>Estimated Record: 3.05 W - 0.95 L</p>
        <h2> September 26 - Vs. Florida State</h2>
        <p>I will start off by admitting my bias here: I absolutely hate Florida State. FSU might be my single least favorite university in the country, and I think the school’s traditions are just obnoxious. If FSU and VT were playing each other, I would root for VT 100% of the time. Giving credit where credit is due, I still think this will be a coin-flip matchup for UVA. Nobody, not even the annoying FSU fans, know where the FSU team we see this year will be the 2-10 team we saw last year, or the 12-0 team we saw two years ago. Purely due to it being a home-field, nationally televised Friday night game, I will give UVA the edge here.</p>
        <p>Chance of Victory: 55%</p>
        <p>Predicted Score: UVA 27 - FSU 24</p>
        <p>Estimated Record: 3.6 W - 1.4 L</p>
        <h2> October 4 - At Louisville</h2>
        <p>In what will likely be UVA’s most difficult matchup of the season, the Cavaliers travel to Louisville to take on the Cardinals. Shockingly, this could end up being UVA’s only matchup against a top-25 team the entire season. UVA has played Louisville closely under Tony Elliott, losing by less than a touchdown in the most recent two matchups. It is certainly possible for UVA to pull off the upset here, but the home-field advantage and talent difference are just too much to overlook to expect a UVA victory. Still, I expect this game to be close, as it has been in previous years.</p>
        <p>Chance of Victory: 30%</p>
        <p>Predicted Score: UVA 17 - LOU 23</p>
        <p>Estimated Record: 3.9 W - 2.1 L</p>
        <figure className="note-figure">
            <img src={louisville} alt="UVA lost a close matchup to Louisville last year in a game with extremely poor attendance." className="note-inline-image" />
            <figcaption>UVA lost a close matchup to Louisville last year in a game with extremely poor attendance.</figcaption>
            <span className="image-source"><a href='https://virginiasports.com/imgproxy/ncCG82zohLkCgad8cRJm6OIlOqYPjx1-18NW3Luwmfo/fit/1920/1080/ce/0/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3Zpcmdpbmlhc3BvcnRzLWNvbS8yMDI0LzEwL1RIXzg3ODQuanBn.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2> October 18 - Vs. Washington State</h2>
        <p>To be honest, I am not exactly sure how this game got on the schedule. Unsurprisingly, considering the schools are over 2000 miles away from each other, this is the first matchup between UVA and WSU. The story of Virginia vs. Washington State is a story of how the transfer portal can both make and break teams. UVA has brought in a much better team using its position in a power four conference and by having boatloads of donations. Washington State has lost its conference, its best players, and even its head coach over the past two seasons. Especially due to the distance Washington State has to travel, this should be an easy win for UVA.</p>
        <p>Chance of Victory: 80%</p>
        <p>Predicted Score: UVA 38 - WSU 20</p>
        <p>Estimated Record: 4.7 W - 2.3 L</p>
        <h2> October 25 - At North Carolina</h2>
        <p>In contrast to the first-ever matchup between Washington State and UVA the week before, UNC and UVA will be playing for the 130th time in what has been deemed the “South’s Oldest Rivalry.” UVA upset 10th-ranked UNC on the road two years ago, in the program’s first-ever road victory over a top 10 team. However, UVA also got absolutely obliterated last year by UNC in what I believe was the most heartbreaking and disappointing UVA game that I have ever been to, which is certainly saying something. This game has many unknowns, especially with Coach Belichick (and his 25-year-old girlfriend) at the helm of UNC. I give the edge to Carolina due to home-field advantage and their more talented roster.</p>
        <p>Chance of Victory: 40%</p>
        <p>Predicted Score: UVA 20 - UNC 27</p>
        <p>Estimated Record: 5.1 W - 2.9 L</p>
        <figure className="note-figure">
            <img src={unc} alt="UVA got demolished at home last year by UNC in the most depressing football game I have ever been to." className="note-inline-image" />
            <figcaption>UVA got demolished at home last year by UNC in the most depressing football game I have ever been to.</figcaption>
            <span className="image-source"><a href='https://virginiasports.com/imgproxy/ZX2cvFy6JXhp9JvR7KRmZnJFXCcPqVWhq0ons-u64ic/fit/1920/1080/ce/0/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3Zpcmdpbmlhc3BvcnRzLWNvbS8yMDI0LzEwL1RIXzA0NjcuanBn.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2> November 1 - At California</h2>
        <p>On the first day in November, UVA will somehow be taking on its third team this season from a west-coast state. The key difference for this matchup is that Cal is marginally better than the other two west-coast teams UVA is playing, and the game is on the road. On paper, UVA should be a better team than Berkeley, but the 2000-mile plane ride after a tough road matchup against UNC is hard to overlook. Fortunately, Cal fans are some of the few fans who show up less to football games than UVA fans. I give UVA a very slight edge in this toss-up game, as I think some people overestimate Cal’s home-field advantage.</p>
        <p>Chance of Victory: 55%</p>
        <p>Predicted Score: UVA 30 - Cal 27</p>
        <p>Estimated Record: 5.65 W - 3.35 L</p>
        <h2> November 8 - Vs. Wake Forest</h2>
        <p>To be honest, I have absolutely nothing to say about Wake Forest. I have always considered it to be the most generic school in the ACC. It is a good school academically, but outside of that it is difficult to name a single interesting fact about Wake. Especially in football, Wake Forest has struggled in recent years, with most analysts putting them as a bottom-three team in the ACC. A worse UVA team was able to beat Wake Forest on the road last year in one of the most exciting football games I have ever watched. Now that UVA is more talented and at home, this game should be a relatively easy win.</p>
        <p>Chance of Victory: 70%</p>
        <p>Predicted Score: UVA 33 - WAKE 20</p>
        <p>Estimated Record: 6.35 W - 3.65 L</p>
        <h2> November 15 - At Duke</h2>
        <p>Historically, a UVA at Duke matchup would be must-see TV for basketball fans, while remaining a much smaller footnote for football viewers. This year should be an exception to that rule, as both teams have quietly been improving over the past few years. Duke achieved an impressive 9-3 season last year, and has kept much of their previous talent. UVA shockingly beat Duke in Charlottesville two years ago, giving Tony Elliott his final win in the 2023 season. This year, the game is on the road for UVA, and Duke has a more talented roster, so I struggle to see UVA pulling off the upset here.</p>
        <p>Chance of Victory: 35%</p>
        <p>Predicted Score: UVA 24 - DUKE 31</p>
        <p>Estimated Record: 6.7 W - 4.3 L</p>
        <h2> November 29 - Vs. Virginia Tech</h2>
        <p>The final matchup of the season, as always, takes place against in-state rival VPI. Doing some research, a lot of sports analysts are picking UVA to win this game in a close matchup. Virginia Tech has lost a lot of its talent to players graduating, and has been constantly disappointing in the past few seasons. UVA should also benefit from home-field advantage and an energized crowd after already clinching a bowl game. Unfortunately for us UVA fans, Benjamin Franklin said there are only three things certain in life: Death, Taxes, and UVA losing to VT on Thanksgiving Weekend. UVA has somehow managed to lose 19 out of the last 20 games to VT, including a brutal 55-17 home loss two years ago. I refuse to get my hopes up and will not be tricked this time into picking UVA to win this one. The curse will remain unbroken.</p>
        <p>Chance of Victory: 30%</p>
        <p>Predicted Score: UVA 17 - VT 30</p>
        <p>Estimated Record: 7.0 W - 5.0 L</p>
        <figure className="note-figure">
            <img src={tech} alt="An image I took two years at the UVA vs. VT game. There is no way you would think this is a UVA home game." className="note-inline-image" />
            <figcaption>An image I took two years at the UVA vs. VT game. There is no way you would think this is a UVA home game.</figcaption>
        </figure>
        <h2>2025 ACC Football Standings</h2>
        <p>All in all, I have UVA with an estimated 7-5 end of season record. This should be good enough for Coach Elliott to keep his job. More importantly for UVA fans, Tony Elliott goes 6-1 at home, finally bringing some turnout and excitement to Scott Stadium. The best solution to a school’s football culture is simple: winning. People will be much more tolerant of a seven dollar hotdog if the team is winning 30-17 than if they are losing 42-10.</p>
        <p>To close this out, <a href="https://playoffpredictors.com/CFBFootball/ACC?L=Iw0JhDLL1OEVjZtLBujzFyd+dFTTLaNNA8JIA" target="_blank" rel="noopener noreferrer">I have attached a link</a> to my entire ACC game-by-game predictions, including none-conference games. I do not have enough time to list reasoning for each game, and I only spent a few seconds predicting each game, so do not take this too seriously. Here are my predicted ACC final standings:</p>
        <ol className="note-list">
            <li className="list-element">Miami (11-1, 8-0)</li>
            <li className="list-element">Clemson (11-1, 7-1)</li>
            <li className="list-element">Southern Methodist (10-2, 6-2)</li>
            <li className="list-element">Georgia Tech (9-3, 6-2)</li>
            <li className="list-element">Louisville (9-3, 5-3)</li>
            <li className="list-element">Duke (8-4, 5-3)</li>
            <li className="list-element">North Carolina (8-4, 4-4)</li>
            <li className="list-element">NC State (7-5, 4-4)</li>
            <li className="list-element">Virginia (7-5, 4-4)</li>
            <li className="list-element">Florida State (6-6, 4-4)</li>
            <li className="list-element">Pittsburgh (6-6, 4-4)</li>
            <li className="list-element">Virginia Tech (6-6, 3-5)</li>
            <li className="list-element">Syracuse (5-7, 3-5)</li>
            <li className="list-element">Boston College (4-8, 2-6)</li>
            <li className="list-element">California (5-7, 2-6)</li>
            <li className="list-element">Stanford (2-10, 1-7)</li>
            <li className="list-element">Wake Forest (4-8, 0-8)</li>
        </ol>

        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
