//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
import bell from './bell.jpg';
import cover from './cover.jpg';
import kennedy from './kennedy.jpg';
import mac from './mac.jpg';
export default function Note5() {
    const noteIndex = 5;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>Across the Board</h2>
        <p>Whenever I get asked what my favorite genre of music is, or what my favorite song is, my answer is always “I will really listen to anything.” A little bit of the reason I answer that is because I am always slightly embarrassed to talk about what songs I listen to, because sometimes they can be rather strange. However, the main reason I answer that is because it really is true. I do not have a Spotify account or any “playlists” of songs. A few years ago I tried to set up some playlists of my favorite songs, but I quickly got bored of the feature after listening to the same songs over and over again. I usually cannot listen to the same song for more than a month or two before I need a break from it.</p>
        <p>This is unrelated to the topic, but I have a theory that enjoyment of a song falls along a normal distribution over time. When you first hear a song, you do not appreciate all of the intricacies of the song, and its lyrics and layers. Then, once you have heard it a few times, you can start looking at more details of the song, and you enjoy it a lot more. Finally, when you hear it too many times, the song starts to get old, and you don’t enjoy it that much anymore.</p>
        <p>For example, this happened to myself with “<a href="https://www.youtube.com/watch?v=IwOfCgkyEj0" target="_blank" rel="noopener noreferrer">Like a Rolling Stone</a>” by Bob Dylan. I remember looking at Rolling Stone Magazine’s <a href="https://www.rollingstone.com/music/music-lists/best-songs-of-all-time-1224767/bob-dylan-like-a-rolling-stone-3-1225334/" target="_blank" rel="noopener noreferrer">500 Best Songs of All Time</a> and seeing Like a Rolling Stone at number 1, and being confused because I did not think it was that great of a song. However, after listening to it about 10 times at different occasions, I really began to appreciate chord progression and themes, which were especially daring for the 1960s. Finally, after hearing it about 100 times, I got a bit sick of it and do not listen to it as much anymore.</p>
        <p>Back to the original topic, because I dislike hearing any single song too much, one of my goals is to explore many different fields and genres of music. This allows me to avoid getting to the point where I run out of new music to listen to. Over the past month, I have decided to take this a step further and go to concerts and performances in genres that are as far apart as possible. I ended up finding three different events that I could make it to (and convince others to go along with me). I was pretty satisfied with how unique they all were, and since I have not written much about myself over the past few notes, I will describe them here.</p>
        <figure className="note-figure">
            <img src={bell} alt="The bell curve of the enjoyment of a song over time." className="note-inline-image" />
            <figcaption>The bell curve of the enjoyment of a song over time.</figcaption>
            <span className="image-source"> <a href={bell} target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>Dreams and Rumo(u)rs</h2>
        <p>While I was aware of Fleetwood Mac before this concert, I was never the biggest fan of them and probably could not name more than five of their songs before this. I knew they made a bunch of famous songs, but I just considered them to be another generic 70s rock band without too much interesting else about them. The concert I went to completely changed my perspective of that idea. The cover band performed the entirety of their 1977 album <a href="https://en.wikipedia.org/wiki/Rumours_\(album\" target="_blank" rel="noopener noreferrer">Rumours</a>), periodically interjecting with facts about the band and the troubled recording history of the album.</p>
        <p>I had no idea how many incredibly famous songs were on this single album. <a href="https://www.youtube.com/watch?v=PgagPdVM7bk" target="_blank" rel="noopener noreferrer">Dreams</a> was ranked as a top ten song of all time by Rolling Stone Magazine. I don’t think it is that good, but it is still a very innovative song for the time. Other famous songs on the album I had heard before include <a href="https://www.youtube.com/watch?v=0hGhl7ki3HM" target="_blank" rel="noopener noreferrer">Don't Stop</a>, <a href="https://www.youtube.com/watch?v=kVE4aOUX2iM" target="_blank" rel="noopener noreferrer">Silver Springs</a> (shoutout Maryland), and <a href="https://www.youtube.com/watch?v=oiosqtFLBBA" target="_blank" rel="noopener noreferrer">Go Your Own Way</a>. Most notably, “Go Your Own Way” is one of those <a href="https://www.youtube.com/watch?v=Zx0raCdepfw" target="_blank" rel="noopener noreferrer">songs you hear in drug commercials</a> where the characters are happily <a href="https://www.youtube.com/watch?v=tQRwx6KMsDY" target="_blank" rel="noopener noreferrer">bowling or golfing</a> while the narrator says “Side effects may include total organ failure and death.”</p>
        <p>The most interesting part of the concert was the cover band’s commentary over the album’s recording problems. Fleetwood Mac keyboardist Christine McVie and bassist John McVie were getting divorced, and vocalists Lindsey Buckingham and Stevie Nicks were also ending their long-term relationship. For example, “Go Your Own Way” was written by Lindsey as a message to Stevie during the end of their relationship. It must have been awkward recording some of these songs. Anyway, the concert gave a great insight into the intricacies of the album and its history. I particularly enjoyed the discussion regarding the layout of the track listing album, since album order is something people rarely think about nowadays.</p>
        <figure className="note-figure">
            <img src={mac} alt="A boring picture of Fleetwood Mac since I forgot to take pictures." className="note-inline-image" />
            <figcaption>A boring picture of Fleetwood Mac since I forgot to take pictures.</figcaption>
            <span className="image-source"> <a href='https://upload.wikimedia.org/wikipedia/commons/f/fe/Fleetwood\_Mac\_Billboard\_1977.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>Revenge of the Germans</h2>
        <p>Last year, a friend invited me to go with him to see a metal band called “Herr Metal” that he was going to for his birthday. I had never been the biggest fan of the genre, but I decided to go along just because of how curious I was. It was certainly an interesting experience, so much so that I decided to go see the same band perform again this year, this time with some more friends. I have listened to more metal music since then, so I would be able to appreciate the performance a bit more.</p>
        <p>The concert started with a performance from a more traditional-style band called Dr. Fu. Dr. Fu played some pretty standard and slightly overplayed, but still enjoyable songs ranging from “Mr. Brightside” to “I Want It That Way.” However, Dr. Fu held a dirty secret: they were actually Herr Metal in disguise. (Or more accurately, not in disguise, as you will see.) They closed out with a performance of “Enter Sandman,” which most people loved, but I could not fully enjoy, since Enter Sandman is the infamous entrance song of Virginia Tech Football. No way I could support a Virginia Tech song, especially since the VT football entrance is quite underwhelming in person for all it is hyped up to be. I will discuss that more another time.</p>
        <p>After about a 30 minute vocal break, Dr. Fu changed into their costumes and emerged as Herr Metal. The premise of the band is that they are a German band on tour in the US, so they all speak with silly German accents. The drummer did not speak at all though, and while the “official” reason was that he had blown out his voice yelling too much on stage, I think the actual reason was that he could not do the German accent well enough. I respect it either way. They played a lot of Bon Jovi and Guns and Roses especially which I enjoyed. I won’t describe the music too much since it can just be looked up, but it was a good listen overall. Even as someone who is not a big metal fan, it was a great experience.</p>
        <figure className="note-figure">
            <img src={cover} alt="A low effort snapshot from the start of the concert." className="note-inline-image" />
            <figcaption>A low effort snapshot from the start of the concert.</figcaption>
            <span className="image-source"> <a href={cover} target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2>A Night at the Opera</h2>
        <p>Finally, in a performance that could not be as far removed from a metal concert, I recently saw Les Miserables at the Kennedy Center in DC. I had never read the original novel or watched the movie, but I was aware of the general plot and historical context behind the musical. Thus, I was very excited to see a full performance of one of the most famous modern musicals. I wish I had time to read the novel before seeing the play, but unfortunately Hugo’s original story is about 1,500 pages long, so I relied on a mere summary instead.</p>
        <p>The performance itself was phenomenal. I had not seen a musical in quite awhile, so this was definitely a good one to start out with. I was paying the most attention to the pit orchestra since they were performing some relatively difficult songs and had to play nonstop since Les Miserables is almost entirely sung-through. The actors were all great, which is to be expected since it is the Kennedy Center after all, and the set was well made. It was certainly better than my eighth grade performance of The Wizard of Oz in middle school. There is no reason to say much more about the performance itself since it was obviously good and there are better reviewers out there than myself.</p>
        <p>The only thing I was disappointed by was a part of the musical itself. There is a serious lack of historical background given within the musica or in the prologuel. The play centers around a group of students rebelling against the French Monarchy, but the musical gives almost no background as to why the students are rebelling. In fact, I would take a bet any day that a majority of the people in the theater would walk out of the musical thinking that Les Miserables was set during the French Revolution. In reality, only the very first scene takes place in the last year of the French Revolution, and the rebellion in the play is actually the 1832 June Rebellion.</p>
        <p>Overall though, it was well worth the time to see the musical. Of the three performances, I would rate this one the highest, although that should not be a surprise given how much more expensive it was. Second place would be Herr Metal and Dr. Fu just for how absurd the whole concept of a fake German metal band is.Third was the Fleetwood Mac cover band, but it was still fun. At least the food was much cheaper than the twenty dollar Kennedy Center salad. The Kennedy Center food prices were the real scam of all of this. It was so expensive I was almost forced to <a href="https://www.youtube.com/watch?v=SEaAXca89vQ" target="_blank" rel="noopener noreferrer">steal a loaf of bread</a> just to feed my family\! I can see why Les Miserables is so realistic now...</p>
        <figure className="note-figure">
            <img src={kennedy} alt="A picture from inside the Kennedy Center before Les Mis started." className="note-inline-image" />
            <figcaption>A picture from inside the Kennedy Center before Les Mis started.</figcaption>
            <span className="image-source"> <a href={kennedy} target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>

        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
