//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
export default function Note20() {
    const noteIndex = 20;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2>Page Under Development</h2>
        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}