//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';
import block from './block.jpg';
import drill from './drill.jpg';
import halftime from './halftime.jpg';
import onfield from './onfield.jpg';
export default function Note10() {
    const noteIndex = 10;
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex - 1];
    const nextNote = notes_list[noteIndex + 1];

    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>
        <h2> Turnaround at Scott Stadium</h2>
        <p>Two months ago, I published my <a href="https://www.josephmoran.org/notes/elliott" target="_blank" rel="noopener noreferrer">2025 UVA football predictions</a> before the start of the Cavaliers’ unexpected season. In my predictions, I repeatedly referenced many past UVA football games that I had the unfortunate experience of watching in their entirety while a student at the University of Virginia. Notable home stinkers I attended in full include the <a href="https://www.espn.com/college-football/game/_/gameId/401525542/georgia-tech-virginia" target="_blank" rel="noopener noreferrer">45-17 drubbing by Georgia Tech</a>, a <a href="https://www.espn.com/college-football/game/_/gameId/401635598/north-carolina-virginia" target="_blank" rel="noopener noreferrer">41-14 choke to a bad UNC team</a>, another <a href="https://www.espn.com/college-football/game/_/gameId/401635619/smu-virginia" target="_blank" rel="noopener noreferrer">33-7 pounding by SMU</a>, and probably worst of all, a <a href="https://www.espn.com/college-football/game/_/gameId/401525564/virginia-tech-virginia" target="_blank" rel="noopener noreferrer">55-17 defeat to rival Virginia Tech</a> that was somehow was even less close than the score would suggest. Of course, the reason I stayed at all of these games in full was due to my involvement in the <a href="https://en.wikipedia.org/wiki/Cavalier_Marching_Band" target="_blank" rel="noopener noreferrer">UVA marching band</a>. I had previously committed to supporting the football team no matter how dire the situation got.</p>
        <p>This year, that commitment has clearly paid off, with the “Cardiac Cavs” now sitting at 8-1 and sitting alone at the top of the ACC at the time of publication. The activity I have been asked the most about in college is my involvement in the marching band, and now that the season has been completely turned around, I figured I would show how a Power 4 marching band like UVA prepares for a home football game. Fortunately, I had previously captured footage using a GoPro during the band rehearsals prior to the <a href="https://www.espn.com/college-football/game/_/gameId/401754539/stanford-virginia" target="_blank" rel="noopener noreferrer">Virginia vs. Stanford</a> football matchup, and I feel it describes the experience quite well. I have compiled some of the clips into a video linked below, and I will go further in-depth into some possibly confusing aspects of marching band for those who are unfamiliar.</p>
        <div class="video-container">
        <iframe 
            src="https://www.youtube.com/embed/4h0vC_tdmz4?si=Dm3yDZEzRZSok3W_"
            title="YouTube video player"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; fullscreen; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin"
            allowfullscreen>
        </iframe>
        </div>
        <h2> Wednesday - Individual Practice</h2>
        <p>The usual practice schedule for our marching band is Tuesdays and Thursdays from 6:00–8:15 PM, and Fridays from 6:30–8:30 if there is a home football game that week. The exact specifics of what is accomplished during a practice depends on the time between home football games. The Stanford football game was the week after the previous home game against William and Mary, so there was limited time to prepare. The time-constrained practice schedule was further compounded by Tuesday thunderstorm, meaning the band was unable to practice movements on the field due to heavy rain.</p>
        <p>The video begins early in the morning with me practicing individually in the Old Cabell Hall practice rooms. Due to the time crunch, I needed to work on memorizing the music individually. My memorization technique is to play through the music twice while looking at the music, and then repeatedly play troubling sections. Then, I will try to play through as much as I can without looking at the music as the background track plays. Memorization is critical, since no music is used on the field. I then proceed to lunch and my classes for the day. I briefly include footage of lunch, mostly because I want to show off how unfortunately subpar the food can be at the UVA dining halls. The class shown is database systems, for all the database programmers and SQL experts reading this.</p>
        <figure className="note-figure">
            <img src={block} alt="UVA football ended the game with a huge victory over Stanford, starting their (as of now) undefeated ACC run." className="note-inline-image" />
            <figcaption>UVA football ended the game with a huge victory over Stanford, starting their (as of now) undefeated ACC run.</figcaption>
            <span className="image-source"><a href='https://virginiasports.com/imgproxy/TMziUYmSUylLgHIqIwamvEFWY9veX8IjhKA1wmvWdOI/fit/1500/1500/ce/0/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3Zpcmdpbmlhc3BvcnRzLWNvbS8yMDI1LzA5LzAwNDhfMjAyNTA5MjBfRkJfR2FsbGVyeS5qcGc.jpg' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2> Thursday - Learning Movements</h2>
        <p>Marching band consists of two semi-intertwined and equally important parts that are best learned separately at first, and then combined later. First, there are the movements of the marcher between different locations on the field, known formally as “drill.” Second, marchers need to learn and memorize the music that will be played while moving around. Since we already practiced the music on Tuesday during the rain, Thursday was devoted to learning drill.</p>
        <p>I believe the question most frequently asked about marching band is something along the lines of, “How does everyone make those pictures without running into each other?” You will notice that during the rehearsal, I frequently look down at a piece of paper that looks almost like a coordinate sheet. Every marching band member has their own “<a href="https://www.bandtek.com/how-to-read-a-drill-chart/" target="_blank" rel="noopener noreferrer">drill chart</a>,” which details the location and direction each member is to move towards on the field. These drill charts are generated by various computer programs, which (ideally) ensure that no two people will ever be in the same location at once when moving between locations.</p>
        <p>Throughout rehearsal, we will practice certain movements between locations repeatedly to ensure everyone can memorize where they are going. Repetition is critical, since a single person forgetting where to move will be very obvious to anyone watching. Throughout rehearsal, the band director will watch from a podium and give constructive feedback on how the band is performing, and what movements need to be relearned. It is also encouraged to count out loud the beats of the song being performed, to help other marchers remember where they are in their drill.</p>
        <figure className="note-figure">
            <img src={drill} alt="The drill sheet I used while determining where to move on the field." className="note-inline-image" />
            <figcaption>The drill sheet I used while determining where to move on the field.</figcaption>
            <span className="image-source"><a href={drill} target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2> Friday - Adding Music</h2>
        <p>After individually learning the drill and the music, the final step is to put the two together. On Friday, the goal was to run all through the songs being performed, while successfully performing the entire drill and playing the music. This performance proved to be unique, since we had two guest brass quintets performing as we marched. Since this is the first time we are performing while playing music, and not everyone has it memorized yet, we have the choice to carry our music on the field with us while we are moving. I usually prefer not to use the music while practicing, since reading music while marching often causes me to get distracted from my drill. However, I was really struggling with memorization due to the short time frame, so I needed a little bit of extra time with the sheet music.</p>
        <p>You should be able to notice that the drill we did on Thursday is the same drill we are performing on Friday, and that generally speaking we are moving in the exact same way. If there is an issue with the drill, we will temporarily stop playing music, and instead briefly work on finding the right place to stand on the field. The music director will be watching from a bird’s-eye view to ensure both the music and drill are being performed correctly. Unfortunately, my camera was angled quite high, so it may be difficult to see the field at times while I am playing. This is because marching with a trumpet, it is ideal to tilt your head up approximately five degrees.</p>
        <figure className="note-figure">
            <img src={halftime} alt="The final halftime performance, taking place at Scott Stadium." className="note-inline-image" />
            <figcaption>The final halftime performance, taking place at Scott Stadium.</figcaption>
            <span className="image-source"><a href='https://www.youtube.com/watch?v=MisqlWcYiK0' target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>
        <h2> Saturday - Gameday</h2>
        <p>The final practice before the game started at 2pm on Saturday. The game against Stanford was (shockingly for how bad they are) at 7pm, and we always start rehearsing about five hours before the game. The final task before going to the game was to perform a complete run of the entire halftime performance, from start to finish. We were joined by the two professional quintets that were the main features of the performance. The first clip on Saturday is our final run-through of the show before leaving for Scott Stadium. Unfortunately, while performing at Scott Stadium, my camera ran out of battery, so I do not have footage of that performance. The audio and the picture-in-picture view of the entire band come from the <a href="https://www.youtube.com/watch?v=5MXD9aypJBo" target="_blank" rel="noopener noreferrer">Paul Thomas YouTube channel</a>, whom I thank for the footage. I mess up my drill once in this rehearsal; see if you can spot where.</p>
        <p>The last section of the view is my POV of the band’s performance of our “pregame show.” Approximately 20 minutes before the start of every game, the band runs out of the football tunnels and performs some of UVA’s school songs to rally the crowd. Unlike the halftime shows, the pregame show is the same for every game, so we spend limited time practicing it during rehearsals. The picture-in-picture footage again comes from the <a href="https://www.youtube.com/watch?v=YUu10jndSow" target="_blank" rel="noopener noreferrer">Paul Thomas YouTube channel</a>, although the audio this time is from my perspective.</p>
        <p>In the end, the game ended up being a huge 48-20 victory for UVA, and was the school’s first victory in ACC play. While this game had relatively low attendance, the stunning victory over FSU the next week would begin to draw huge crowds to UVA football, and the season has only gotten better from there. I could not have possibly imagined that UVA would be undefeated in football at this point in time. Hopefully, against Wake Forest next weekend, there will be huge crowds and a huge victory. Regardless of the outcome, though, the marching band will always be there.</p>
        <figure className="note-figure">
            <img src={onfield} alt="Myself on the field against Stanford, after performing the pregame show." className="note-inline-image" />
            <figcaption>Myself on the field against Stanford, after performing the pregame show.</figcaption>
            <span className="image-source"><a href={onfield} target="_blank" rel="noopener noreferrer">Source</a></span>
        </figure>

        <div className="note-nav">
            {prevNote && <Link to={`${window.location.pathname}/../${prevNote.link}`} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={`${window.location.pathname}/../${nextNote.link}`} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}
